<a href="https://colab.research.google.com/github/Omarctr/Machine-Learning/blob/main/Kfold_Cross_validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits, load_iris

dig = load_digits()
dir(dig)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [ ]:
from sklearn.model_selection import train_test_split

x = dig.data
y = dig.target

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)

In [ ]:
lr = LogisticRegression(max_iter = 1000)
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

0.9685185185185186

In [ ]:
svm = SVC(C = 3)
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.9907407407407407

In [ ]:
rfc = RandomForestClassifier()
rfc.fit(x_train, y_train)
rfc.score(x_test, y_test)

0.9685185185185186

In [ ]:
#Now using k fold cross validation

from sklearn.model_selection import KFold

kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [ ]:
for train_index, test_index in kf.split(range(9)):
  print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [ ]:
def get_score(model, x_train, x_test, y_train, y_test):
  model.fit(x_train, y_train)
  return model.score(x_test, y_test)

print(get_score(lr, x_train, x_test, y_train, y_test))
print(get_score(svm, x_train, x_test, y_train, y_test))
print(get_score(rfc, x_train, x_test, y_train, y_test))

0.9685185185185186
0.9907407407407407
0.9703703703703703


In [ ]:
from sklearn.model_selection import StratifiedKFold

fold = StratifiedKFold(n_splits = 3)

In [ ]:
score_lr = []
score_svm = []
score_rfc = []
x = dig.data
y = dig.target
for train_index, test_index in fold.split(x, y):
  x_train, x_test, y_train, y_test = x[train_index], x[test_index], \
                                    y[train_index], y[test_index]

  score_lr.append(get_score(LogisticRegression(max_iter = 1000), x_train, x_test, y_train, y_test))
  score_svm.append(get_score(SVC(), x_train, x_test, y_train, y_test))
  score_rfc.append(get_score(RandomForestClassifier(), x_train, x_test, y_train, y_test))
print(score_lr, '\n', score_svm, '\n', score_rfc)



[0.9198664440734557, 0.9415692821368948, 0.9165275459098498] 
 [0.9649415692821369, 0.9799666110183639, 0.9649415692821369] 
 [0.9298831385642737, 0.9599332220367279, 0.9282136894824707]


# **easier way**

In [ ]:
from sklearn.model_selection import cross_val_score

score_lr = cross_val_score(LogisticRegression(max_iter = 1000), x, y, cv = 4)
print(f'logistic regression: {score_lr.mean()}')

score_svm = cross_val_score(SVC(), x, y, cv = 4)
print(f'SVC: {score_svm.mean()}')

score_rfc = cross_val_score(RandomForestClassifier(), x, y, cv = 4)
print(f'random forest classifier : {score_rfc.mean()}')

logistic regression: 0.927096015837664
SVC: 0.9654998762682504
random forest classifier : 0.9371170502350904


In [ ]:
iris = load_iris()

x = iris.data
y = iris.target

score_lr = (cross_val_score(LogisticRegression(max_iter = 1000), x, y, cv = 10)).mean()
score_svm = (cross_val_score(SVC(C = 10), x, y, cv = 10)).mean()
score_rfc = (cross_val_score(RandomForestClassifier(), x, y, cv = 10)).mean()
print(score_lr, score_svm, score_rfc)

0.9733333333333334 0.9800000000000001 0.96
